-- 0007_introductions_favors_deals_content.sql

-- ---------------------------------------------------------------------------
-- introductions
-- ---------------------------------------------------------------------------
-- Two kinds of row live here:
--
--   * Rows generated by trg_introduced_by from people.introduced_by_person_id.
--     These carry auto_from_person_id and are kept in sync with that field
--     rather than edited independently — the operator never enters an
--     introduction twice.
--   * Manually entered rows, which cover introductions the operator made for
--     other people. Those have no corresponding profile field.

create table introductions (
  id                   uuid primary key default gen_random_uuid(),
  perspective          intro_perspective not null,
  introducer_person_id uuid references people (id) on delete cascade,
  party_a_person_id    uuid references people (id) on delete cascade,
  party_b_person_id    uuid references people (id) on delete cascade,
  external_party_name  text,
  occurred_on          date,
  outcome              text,
  note                 text,

  -- Set only when the row was generated from a person's introduced_by field.
  auto_from_person_id  uuid references people (id) on delete cascade,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),

  -- "Erica introduced me to Amanda" needs both ends named.
  constraint introductions_received_shape check (
    perspective <> 'received_by_me'
    or (introducer_person_id is not null and party_a_person_id is not null)
  ),
  -- "I introduced Amanda to someone" needs at least one named counterparty.
  constraint introductions_made_shape check (
    perspective <> 'made_by_me'
    or (party_a_person_id is not null and (party_b_person_id is not null or external_party_name is not null))
  ),
  constraint introductions_distinct_parties check (
    party_a_person_id is null or party_b_person_id is null or party_a_person_id <> party_b_person_id
  ),
  constraint introductions_introducer_not_party check (
    introducer_person_id is null
    or (introducer_person_id is distinct from party_a_person_id
        and introducer_person_id is distinct from party_b_person_id)
  )
);

-- One auto row per person: the upsert target for trg_introduced_by.
create unique index introductions_auto_key
  on introductions (auto_from_person_id)
  where auto_from_person_id is not null;

create index introductions_introducer_idx on introductions (introducer_person_id) where introducer_person_id is not null;
create index introductions_party_a_idx    on introductions (party_a_person_id) where party_a_person_id is not null;
create index introductions_party_b_idx    on introductions (party_b_person_id) where party_b_person_id is not null;

create trigger trg_introductions_updated_at
  before update on introductions
  for each row execute function fn_touch_updated_at();

-- ---------------------------------------------------------------------------
-- favors
-- ---------------------------------------------------------------------------
-- direction is from the operator's point of view: 'gave' means the operator did
-- this person a favor, 'received' means this person did the operator one.

create table favors (
  id          uuid primary key default gen_random_uuid(),
  person_id   uuid not null references people (id) on delete cascade,
  direction   favor_direction not null,
  kind        favor_kind not null default 'other',
  occurred_on date not null default current_date,
  description text,
  value_note  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index favors_person_idx on favors (person_id, occurred_on desc);

create trigger trg_favors_updated_at
  before update on favors
  for each row execute function fn_touch_updated_at();

-- ---------------------------------------------------------------------------
-- deals — attribution stubs, not a pipeline
-- ---------------------------------------------------------------------------
-- This table exists to answer "which relationships and which rooms actually
-- produced". It is not a place to manage live transactions.

create table deals (
  id                          uuid primary key default gen_random_uuid(),
  name                        text not null,
  counterparty_organization_id uuid references organizations (id) on delete set null,
  source_person_id            uuid references people (id) on delete set null,
  source_organization_id      uuid references organizations (id) on delete set null,
  stage                       deal_stage not null default 'referred',
  amount_cents                bigint,
  referred_on                 date,
  closed_on                   date,
  external_ref                text,
  commission_terms            text,
  commission_earned_cents     bigint,
  commission_paid_cents       bigint,
  note                        text,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),

  constraint deals_name_present check (btrim(name) <> ''),
  constraint deals_amounts_non_negative check (
    coalesce(amount_cents, 0) >= 0
    and coalesce(commission_earned_cents, 0) >= 0
    and coalesce(commission_paid_cents, 0) >= 0
  ),
  constraint deals_dates_ordered check (closed_on is null or referred_on is null or closed_on >= referred_on),
  constraint deals_funded_has_close_date check (stage <> 'funded' or closed_on is not null)
);

create index deals_source_person_idx on deals (source_person_id) where source_person_id is not null;
create index deals_source_org_idx    on deals (source_organization_id) where source_organization_id is not null;
create index deals_stage_idx         on deals (stage);
create index deals_referred_idx      on deals (referred_on);

create trigger trg_deals_updated_at
  before update on deals
  for each row execute function fn_touch_updated_at();

-- ---------------------------------------------------------------------------
-- content_touches
-- ---------------------------------------------------------------------------
-- What the operator has sent whom. Doubles as the catalog: the distinct set of
-- content_title values is the library, so "an unsent piece" is answerable
-- without a separate table for it.

create table content_touches (
  id            uuid primary key default gen_random_uuid(),
  person_id     uuid not null references people (id) on delete cascade,
  content_title text not null,
  content_ref   text,
  sent_on       date not null default current_date,
  channel       touch_channel not null default 'email',
  response_note text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint content_touches_title_present check (btrim(content_title) <> '')
);

create index content_touches_person_idx on content_touches (person_id, sent_on desc);
create index content_touches_title_idx  on content_touches (lower(content_title), sent_on desc);

create trigger trg_content_touches_updated_at
  before update on content_touches
  for each row execute function fn_touch_updated_at();
